permalink: /:year/:month/:day/:title.html
paginate: 10
#markdown: redcarpet
markdown: kramdown

# Author
author: 
  name: Billy Chen Xiao
  email: billy.chenxiao@gmail.com
  link: chenxiao.cc
  github: http://github.com/chenxiaocc

# Site
title: chen xiao
description: Blog of Billy Chen Xiao
url: http://chenxiao.cc
rss_url: /pages/atom.xml

# gavatar Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics
ga:
  id: UA-54262064-1 
  url: chenxiao.cc

# default active
active: 读书

# 首页除了最新文章外显示分类
# cates:
#   - Optimization
#   - LaTeX

# localization
locals:
  tags: 标签
  about: 关于
  newest: 吃饭睡觉打豆豆
  archive: 存档