permalink: /:year/:month/:day/:title.html
paginate: 10
#markdown: redcarpet
markdown: kramdown

# Author
author: 
  name: Tang Hui
  email: 839283929@qq.com
  link: http://www.tanghui123.com/
  github: http://github.com/TangHui123

# Site
title: 小灰灰
description: Blog of Tang Hui
url: hhttp://www.tanghui123.com/
rss_url: /pages/atom.xml

# gavatar Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics
ga:
  id: UA-54262064-1 
  url: http://www.tanghui123.com/

# default active
active: 读书

# 首页除了最新文章外显示分类
# cates:
#   - Optimization
#   - LaTeX

# localization
locals:
  tags: 标签
  about: 关于
  newest: 吃饭睡觉打豆豆
  archive: 存档